### ISSUE TITLE
Use of exceptions

### ISSUE THREAD

**Issue by HEIC-to-JPEG-Dev** [Arlodotexe/OwlCore.Storage#24]
**Issue:**
Exceptions are used prolifically within the code base; as a simple example, the constructor for SystemFile.

**Reason**
Exceptions should not be used where a known outcome is a possibility; they should be restricted to catastophic events and unexpected outcomes.

There is a massive performance penalty for using exceptions and additional code required for the developer. In file loops, this would bring an app to a halt. 

**Example**
for example: SystemFile x; try { x = new("C:\path") } catch (exception ex) { do something else}
compared to: var x = new SystemFile("C:\path"); 

**Proposal**
Replace exceptions with return values from methods that are more meaningful, for example: null, error code, or valid empty object.

**Comment by Arlodotexe** [comment]
We took cues from what System.IO and Windows.Storage when deciding when to use exceptions.

SystemFile throws in the ctor if the file does not exist, because the file must exist for the instance to be usable. See https://github.com/Arlodotexe/OwlCore.Storage/issues/26#issuecomment-1492316984

Generally, we use exceptions to indicate undesirable states caused by invalid data. We also use exceptions to indicate when a file/folder does not exist on methods where the intent is _not_ to check that it exists, but to do something else (same as .NET).

**Comment by HEIC-to-JPEG-Dev** [comment]
In my libraries, I return null if something is invalid; I also have a common result error system to handle addiitonal data.

**Comment by Arlodotexe** [comment]
It's a recommended .NET STandard [Best Practice](https://learn.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions#throw-exceptions-instead-of-returning-an-error-code) to throw instead of returning an error code.

**Comment by HEIC-to-JPEG-Dev** [comment]
I think my confusion here was the assumption that the library would work with files/folders that change/don't exist.

From my understanding, the library only works with files that exist and do not change state. In that scenario, raising an exception would be correct as a file not existing is not an expected state.
